<a href="https://colab.research.google.com/github/LuisVFCO/pythonLuis/blob/main/Aula_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Aula 4 - Comandos no pandas

In [5]:
meusDados = np.matrix('1, 2, 3; 4, 5, 6; 7, 8, 9; 10, 11, 12')
meusDados

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

Criando dataframe

In [7]:
meuDF = pd.DataFrame(meusDados)
type(meuDF)

pandas.core.frame.DataFrame

In [9]:
meuDF

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

Organizando/criando index

In [10]:
indice = ['Linha ' + str(i) for i in range(4)]

In [11]:
colunas = ['Colunas ' + str(i) for i in range(3)]

In [13]:
df2 = pd.DataFrame (data= meusDados, index= indice, columns= colunas)
df2

Colunas 0  Colunas 1  Colunas 2
Linha 0          1          2          3
Linha 1          4          5          6
Linha 2          7          8          9
Linha 3         10         11         12

In [14]:
df2 = pd.DataFrame(meusDados, indice, colunas)
df2

Colunas 0  Colunas 1  Colunas 2
Linha 0          1          2          3
Linha 1          4          5          6
Linha 2          7          8          9
Linha 3         10         11         12

DataFrame manual

In [25]:
df3 = {'Coluna0': {'Linha0': 1, 'Linha1': 4, 'Linha2': 7},
     'Coluna1': {'Linha0': 2, 'Linha1': 5, 'Linha2': 8},
     'Coluna2': {'Linha0': 3, 'Linha1': 6, 'Linha2': 9}
}
df3

{'Coluna0': {'Linha0': 1, 'Linha1': 4, 'Linha2': 7},
 'Coluna1': {'Linha0': 2, 'Linha1': 5, 'Linha2': 8},
 'Coluna2': {'Linha0': 3, 'Linha1': 6, 'Linha2': 9}}

In [29]:
df3 = pd.DataFrame(df3)
df3

Coluna0  Coluna1  Coluna2
Linha0        1        2        3
Linha1        4        5        6
Linha2        7        8        9

Concatenando Data Frames:

In [30]:
df4 = pd.concat([meuDF, df2, df3])
df4

0     1     2  Colunas 0  Colunas 1  Colunas 2  Coluna0  Coluna1  \
0         1.0   2.0   3.0        NaN        NaN        NaN      NaN      NaN   
1         4.0   5.0   6.0        NaN        NaN        NaN      NaN      NaN   
2         7.0   8.0   9.0        NaN        NaN        NaN      NaN      NaN   
3        10.0  11.0  12.0        NaN        NaN        NaN      NaN      NaN   
Linha 0   NaN   NaN   NaN        1.0        2.0        3.0      NaN      NaN   
Linha 1   NaN   NaN   NaN        4.0        5.0        6.0      NaN      NaN   
Linha 2   NaN   NaN   NaN        7.0        8.0        9.0      NaN      NaN   
Linha 3   NaN   NaN   NaN       10.0       11.0       12.0      NaN      NaN   
Linha0    NaN   NaN   NaN        NaN        NaN        NaN      1.0      2.0   
Linha1    NaN   NaN   NaN        NaN        NaN        NaN      4.0      5.0   
Linha2    NaN   NaN   NaN        NaN        NaN        NaN      7.0      8.0   

         Coluna2  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
Linha 0      NaN  
Linha 1      NaN  
Linha 2      NaN  
Linha 3      NaN  
Linha0       3.0  
Linha1       6.0  
Linha2       9.0

NaN = Not a Number

Corrigindo o NaN:

In [31]:
df4.isnull()

0      1      2  Colunas 0  Colunas 1  Colunas 2  Coluna0  \
0        False  False  False       True       True       True     True   
1        False  False  False       True       True       True     True   
2        False  False  False       True       True       True     True   
3        False  False  False       True       True       True     True   
Linha 0   True   True   True      False      False      False     True   
Linha 1   True   True   True      False      False      False     True   
Linha 2   True   True   True      False      False      False     True   
Linha 3   True   True   True      False      False      False     True   
Linha0    True   True   True       True       True       True    False   
Linha1    True   True   True       True       True       True    False   
Linha2    True   True   True       True       True       True    False   

         Coluna1  Coluna2  
0           True     True  
1           True     True  
2           True     True  
3           True     True  
Linha 0     True     True  
Linha 1     True     True  
Linha 2     True     True  
Linha 3     True     True  
Linha0     False    False  
Linha1     False    False  
Linha2     False    False

In [32]:
df4.isnull().sum()

0            7
1            7
2            7
Colunas 0    7
Colunas 1    7
Colunas 2    7
Coluna0      8
Coluna1      8
Coluna2      8
dtype: int64

Filtrar Not a Number:

In [34]:
df5 = df4.fillna(df4.mean())
df5

0     1     2  Colunas 0  Colunas 1  Colunas 2  Coluna0  Coluna1  \
0         1.0   2.0   3.0        5.5        6.5        7.5      4.0      5.0   
1         4.0   5.0   6.0        5.5        6.5        7.5      4.0      5.0   
2         7.0   8.0   9.0        5.5        6.5        7.5      4.0      5.0   
3        10.0  11.0  12.0        5.5        6.5        7.5      4.0      5.0   
Linha 0   5.5   6.5   7.5        1.0        2.0        3.0      4.0      5.0   
Linha 1   5.5   6.5   7.5        4.0        5.0        6.0      4.0      5.0   
Linha 2   5.5   6.5   7.5        7.0        8.0        9.0      4.0      5.0   
Linha 3   5.5   6.5   7.5       10.0       11.0       12.0      4.0      5.0   
Linha0    5.5   6.5   7.5        5.5        6.5        7.5      1.0      2.0   
Linha1    5.5   6.5   7.5        5.5        6.5        7.5      4.0      5.0   
Linha2    5.5   6.5   7.5        5.5        6.5        7.5      7.0      8.0   

         Coluna2  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
Linha 0      6.0  
Linha 1      6.0  
Linha 2      6.0  
Linha 3      6.0  
Linha0       3.0  
Linha1       6.0  
Linha2       9.0

Copiando Data Frame:

In [35]:
df8 = df5.copy()

Deletar com dropna:

In [36]:
df4.dropna(inplace = True)
df4

Empty DataFrame
Columns: [0, 1, 2, Colunas 0, Colunas 1, Colunas 2, Coluna0, Coluna1, Coluna2]
Index: []

In [37]:
df5

0     1     2  Colunas 0  Colunas 1  Colunas 2  Coluna0  Coluna1  \
0         1.0   2.0   3.0        5.5        6.5        7.5      4.0      5.0   
1         4.0   5.0   6.0        5.5        6.5        7.5      4.0      5.0   
2         7.0   8.0   9.0        5.5        6.5        7.5      4.0      5.0   
3        10.0  11.0  12.0        5.5        6.5        7.5      4.0      5.0   
Linha 0   5.5   6.5   7.5        1.0        2.0        3.0      4.0      5.0   
Linha 1   5.5   6.5   7.5        4.0        5.0        6.0      4.0      5.0   
Linha 2   5.5   6.5   7.5        7.0        8.0        9.0      4.0      5.0   
Linha 3   5.5   6.5   7.5       10.0       11.0       12.0      4.0      5.0   
Linha0    5.5   6.5   7.5        5.5        6.5        7.5      1.0      2.0   
Linha1    5.5   6.5   7.5        5.5        6.5        7.5      4.0      5.0   
Linha2    5.5   6.5   7.5        5.5        6.5        7.5      7.0      8.0   

         Coluna2  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
Linha 0      6.0  
Linha 1      6.0  
Linha 2      6.0  
Linha 3      6.0  
Linha0       3.0  
Linha1       6.0  
Linha2       9.0

In [39]:
df5.dropna(subset = [1], inplace = True)
df5

0     1     2  Colunas 0  Colunas 1  Colunas 2  Coluna0  Coluna1  \
0         1.0   2.0   3.0        5.5        6.5        7.5      4.0      5.0   
1         4.0   5.0   6.0        5.5        6.5        7.5      4.0      5.0   
2         7.0   8.0   9.0        5.5        6.5        7.5      4.0      5.0   
3        10.0  11.0  12.0        5.5        6.5        7.5      4.0      5.0   
Linha 0   5.5   6.5   7.5        1.0        2.0        3.0      4.0      5.0   
Linha 1   5.5   6.5   7.5        4.0        5.0        6.0      4.0      5.0   
Linha 2   5.5   6.5   7.5        7.0        8.0        9.0      4.0      5.0   
Linha 3   5.5   6.5   7.5       10.0       11.0       12.0      4.0      5.0   
Linha0    5.5   6.5   7.5        5.5        6.5        7.5      1.0      2.0   
Linha1    5.5   6.5   7.5        5.5        6.5        7.5      4.0      5.0   
Linha2    5.5   6.5   7.5        5.5        6.5        7.5      7.0      8.0   

         Coluna2  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
Linha 0      6.0  
Linha 1      6.0  
Linha 2      6.0  
Linha 3      6.0  
Linha0       3.0  
Linha1       6.0  
Linha2       9.0

Deletando colunas inteiras:

In [42]:
df6 = df5.drop(columns = ['Coluna0'])
df6

0     1     2  Colunas 0  Colunas 1  Colunas 2  Coluna1  Coluna2
0         1.0   2.0   3.0        5.5        6.5        7.5      5.0      6.0
1         4.0   5.0   6.0        5.5        6.5        7.5      5.0      6.0
2         7.0   8.0   9.0        5.5        6.5        7.5      5.0      6.0
3        10.0  11.0  12.0        5.5        6.5        7.5      5.0      6.0
Linha 0   5.5   6.5   7.5        1.0        2.0        3.0      5.0      6.0
Linha 1   5.5   6.5   7.5        4.0        5.0        6.0      5.0      6.0
Linha 2   5.5   6.5   7.5        7.0        8.0        9.0      5.0      6.0
Linha 3   5.5   6.5   7.5       10.0       11.0       12.0      5.0      6.0
Linha0    5.5   6.5   7.5        5.5        6.5        7.5      2.0      3.0
Linha1    5.5   6.5   7.5        5.5        6.5        7.5      5.0      6.0
Linha2    5.5   6.5   7.5        5.5        6.5        7.5      8.0      9.0

Deletando linhas inteiras:

In [44]:
df7 = df6.drop(index = [2])
df7

0     1     2  Colunas 0  Colunas 1  Colunas 2  Coluna1  Coluna2
0         1.0   2.0   3.0        5.5        6.5        7.5      5.0      6.0
1         4.0   5.0   6.0        5.5        6.5        7.5      5.0      6.0
3        10.0  11.0  12.0        5.5        6.5        7.5      5.0      6.0
Linha 0   5.5   6.5   7.5        1.0        2.0        3.0      5.0      6.0
Linha 1   5.5   6.5   7.5        4.0        5.0        6.0      5.0      6.0
Linha 2   5.5   6.5   7.5        7.0        8.0        9.0      5.0      6.0
Linha 3   5.5   6.5   7.5       10.0       11.0       12.0      5.0      6.0
Linha0    5.5   6.5   7.5        5.5        6.5        7.5      2.0      3.0
Linha1    5.5   6.5   7.5        5.5        6.5        7.5      5.0      6.0
Linha2    5.5   6.5   7.5        5.5        6.5        7.5      8.0      9.0

Valores Únicos:

In [45]:
df5.Coluna2.unique()

array([6., 3., 9.])

In [46]:
df5.columns.unique()

Index([0, 1, 2, 'Colunas 0', 'Colunas 1', 'Colunas 2', 'Coluna0', 'Coluna1',
       'Coluna2'],
      dtype='object')

In [47]:
df5.index.unique()

Index([        0,         1,         2,         3, 'Linha 0', 'Linha 1',
       'Linha 2', 'Linha 3',  'Linha0',  'Linha1',  'Linha2'],
      dtype='object')

Saida "limpa":

In [48]:
print(df5.Coluna2.unique())

[6. 3. 9.]


In [49]:
print(df5.columns.unique())

Index([0, 1, 2, 'Colunas 0', 'Colunas 1', 'Colunas 2', 'Coluna0', 'Coluna1',
       'Coluna2'],
      dtype='object')


In [50]:
print(df5.index.unique())

Index([        0,         1,         2,         3, 'Linha 0', 'Linha 1',
       'Linha 2', 'Linha 3',  'Linha0',  'Linha1',  'Linha2'],
      dtype='object')


Usando sort_values para "ordenar por":

In [51]:
df8.sort_values(by = 'Coluna1')

0     1     2  Colunas 0  Colunas 1  Colunas 2  Coluna0  Coluna1  \
Linha0    5.5   6.5   7.5        5.5        6.5        7.5      1.0      2.0   
0         1.0   2.0   3.0        5.5        6.5        7.5      4.0      5.0   
1         4.0   5.0   6.0        5.5        6.5        7.5      4.0      5.0   
2         7.0   8.0   9.0        5.5        6.5        7.5      4.0      5.0   
3        10.0  11.0  12.0        5.5        6.5        7.5      4.0      5.0   
Linha 0   5.5   6.5   7.5        1.0        2.0        3.0      4.0      5.0   
Linha 1   5.5   6.5   7.5        4.0        5.0        6.0      4.0      5.0   
Linha 2   5.5   6.5   7.5        7.0        8.0        9.0      4.0      5.0   
Linha 3   5.5   6.5   7.5       10.0       11.0       12.0      4.0      5.0   
Linha1    5.5   6.5   7.5        5.5        6.5        7.5      4.0      5.0   
Linha2    5.5   6.5   7.5        5.5        6.5        7.5      7.0      8.0   

         Coluna2  
Linha0       3.0  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
Linha 0      6.0  
Linha 1      6.0  
Linha 2      6.0  
Linha 3      6.0  
Linha1       6.0  
Linha2       9.0

Renomeando uma coluna:

In [52]:
df8.rename(columns = {'Coluna1':'COLUNA 1'}, inplace = True)
df8

0     1     2  Colunas 0  Colunas 1  Colunas 2  Coluna0  COLUNA 1  \
0         1.0   2.0   3.0        5.5        6.5        7.5      4.0       5.0   
1         4.0   5.0   6.0        5.5        6.5        7.5      4.0       5.0   
2         7.0   8.0   9.0        5.5        6.5        7.5      4.0       5.0   
3        10.0  11.0  12.0        5.5        6.5        7.5      4.0       5.0   
Linha 0   5.5   6.5   7.5        1.0        2.0        3.0      4.0       5.0   
Linha 1   5.5   6.5   7.5        4.0        5.0        6.0      4.0       5.0   
Linha 2   5.5   6.5   7.5        7.0        8.0        9.0      4.0       5.0   
Linha 3   5.5   6.5   7.5       10.0       11.0       12.0      4.0       5.0   
Linha0    5.5   6.5   7.5        5.5        6.5        7.5      1.0       2.0   
Linha1    5.5   6.5   7.5        5.5        6.5        7.5      4.0       5.0   
Linha2    5.5   6.5   7.5        5.5        6.5        7.5      7.0       8.0   

         Coluna2  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
Linha 0      6.0  
Linha 1      6.0  
Linha 2      6.0  
Linha 3      6.0  
Linha0       3.0  
Linha1       6.0  
Linha2       9.0